config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users
      resources :links
      resources :votes

      root to: "users#index"
    end
  end

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :links, path: "recommended" do
    resource :vote

    member do
      get :go
    end
  end

  root to: "links#index"
end

app/models/link.rb
class Link < ApplicationRecord
  include OpenGraphable

  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :users

  scope :sorted, ->{ order(created_at: :desc) }

  validates :url, presence: true

  def voted_by?(user)
    return false if user.nil?
    votes.where(user_id: user.id).any?
  end
end

app/controllers/admin/links_controller.rb
module Admin
  class LinksController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Link.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Link.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :go]

  # GET /links
  # GET /links.json
  def index
    @links = Link.sorted
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
  end

  def go
    @link = Link.find(params[:id])
    @link.increment! :view_count
    redirect_to @link.url
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.new(link_params)

    respond_to do |format|
      if @link.save
        @link.votes.create(user: current_user)
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = if current_user.admin?
                Link.find(params[:id])
              else
                current_user.links.find(params[:id])
              end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:user_id, :title, :link_type, :url, :description, :image)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_about.html.erb
<div class="about">
  <h3>About FeedForward.io</h3>
  <p>Our goal is to link to <b>only</b> the most interesting articles that we come across. They should inspire you, challenge you, and encourage you.<p>
  <p><b>We want every article to create discussions.</b></p>
  <p><%= link_to "http://feeds.feedburner.com/FeedForwardio", class: "btn btn-large btn-primary btn-min-width" do %>Subscribe to our RSS Feed <i class="icon-rss"></i><% end %></p>
  <p><%= link_to podcasts_path, class: "btn btn-large btn-primary btn-min-width" do %>Listen to our Podcast <i class="icon-headphones"></i><% end %></p>
</div>
<hr />

<h4>Feed Contributors</h4>

<div class="contributor">
  <%= link_to avatar_image("excid3@gmail.com"), "http://excid3.com", target: "_blank" %>
  <div class="name"><%= link_to "Chris Oliver", "http://excid3.com" %></div>
  <div class="twitter">
    <a href="https://twitter.com/excid3" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow @excid3</a>
  </div>
</div>
<div class="contributor">
  <%= link_to avatar_image("cosmodrome@gmail.com"), "http://archetyp.al", target: "_blank" %>
  <div class="name"><%= link_to "Rob Long", "http://archetyp.al/", target: "_blank" %></div>
  <div class="twitter">
    <a href="https://twitter.com/plantimals" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow @plantimals</a>
  </div>
</div>

<hr />

<div>
  <strong>Have an article to submit? Want to join us?</strong>
  <br/>
  <%= mail_to "chris@excid3.com?subject=I+want+to+join+FeedForward.io!", "Email us" %> or <%= link_to "send us a tweet", "https://twitter.com/intent/tweet?text=%40excid3+%40plantimals+I+want+to+join+FeedForward.io%21&related=excid3,plantimals" %>.
</div>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, placeholder: "URL", class: "form-control", autofocus: true %>
  </div>

  <% if @link.persisted? %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, placeholder: "Description", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.text_field :image, placeholder: "Image URL", class: "form-control" %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.button "Recommend", class: "btn btn-block btn-primary", data: {disable_with: "Submitting..."} %>
  </div>
<% end %>

app/views/links/_link.html.erb
<%= div_for link, class: "recommended-link" do %>
  <div class="row">
    <div class="col-sm-1">
      <div class="votes">
        <%= render partial: "votes", locals: {link: link} %>
      </div>
    </div>
    <div class="col-sm-9">
      <h2><%= link_to link.title, go_link_path(link), target: :blank %></h2>
      <p class="description"><%= link.description %></p>
      <p class="submitted-by">
        <%= link.link_type.capitalize %> submitted by <%= link.user.try(:name) %>
        | <%= pluralize link.view_count, "view" %>
        | <%= link_to link do %>
            <% content_tag :span, "Comments", class: "disqus-comment-count", data: { disqus_url: link_url(link) } %>
          <% end %>
        <% if user_signed_in? && (current_user.admin? || link.user == current_user) %>
          | <%= link_to "Edit", edit_link_path(link) %>
          | <%= link_to "Delete", link_path(link), method: :delete, data: {confirm: "Are you sure you want to delete this link?"} %>
        <% end %>
      </p>
    </div>
    <div class="col-sm-2">
      <%= link_to image_tag(link.image, class: "img-responsive img-rounded"), go_link_path(link), target: :blank if link.image? %>
    </div>
  </div>
<% end %>

app/views/links/_votes.html.erb
<div class="text-center">
  <% if link.voted_by? current_user %>
    <%= link_to fa_icon("heart", class: "text-hearted"), link_vote_path(link), method: :delete, remote: true %>
  <% elsif user_signed_in? %>
    <%= link_to fa_icon("heart-o", class: "text-muted"), link_vote_path(link), method: :post, remote: true, data: {toggle: "tooltip"}, title: "Recommend this" %>
  <% else %>
    <%= link_to fa_icon("heart-o", class: "text-muted"), new_user_registration_path, data: {toggle: "tooltip"}, title: "Sign up to recommend this" %>
  <% end %>

  <div class="text-muted"><%= link.votes_count %></div>
</div>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1 class="recommended text-center">Recommended Links</h1>

<%= render @links %>

app/views/links/new.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h1 class="text-center">Submit A Link</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/links/show.html.erb
<% content_for :right_nav do %>
  <li><p class="navbar-btn"><%= link_to 'Submit A Link', new_link_path, class: "btn btn-default" %></p></li>
<% end %>

<%= render @link %>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'feedforward';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>